name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
      types: [opened]
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-20.04
    container: raiderrobotics/container-registry:rr-noetic-base
    steps:
      - uses: actions/checkout@v3
      - uses: betwo/github-setup-catkin@master
        with:
          ros-version: 'melodic'
          build-tool: 'catkin_tools'
          workspace: '$GITHUB_WORKSPACE'
      - run: catkin build
      
              
  test:
    needs: build
    runs-on: ubuntu-20.04
    container: raiderrobotics/container-registry:rr-noetic-base
    steps:
    - name: ‚úîÔ∏è Checkout Repository and Submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: üß™ Execute Unit Tests
      run: |
         source /opt/ros/noetic/setup.bash
         catkin_make run_tests

     # Upload coverage result to Coverage.io 
    - name: Upload result to Coveralls.io
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{github.workspace}}/build/coverage.info.cleaned
        fail_ci_if_error: true # optional (default = false)
        verbose: true #
